services:

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    container_name: web-server
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./php/Dockerfile
    container_name: app-service
    volumes:
      - ./app:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  db:
    image: mysql:8.0.33
    volumes:
      - mysqldata:/var/lib/mysql
    container_name: db-server
    restart: unless-stopped
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker-db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

volumes:
  mysqldata: {}